window.addEventListener("load",()=>setTimeout(()=>{const l=document.getElementById("loader");l.style.opacity="0";setTimeout(()=>l.remove(),800)},900));
function scrollToId(id){document.getElementById(id).scrollIntoView({behavior:"smooth"})}
const canvas=document.getElementById("stars"),ctx=canvas.getContext("2d");let stars=[];
function resize(){canvas.width=innerWidth;canvas.height=innerHeight;stars=Array.from({length:100},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*1.4+.2,a:Math.random()}))}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);stars.forEach(s=>{s.a+=.01;ctx.globalAlpha=.25+.3*Math.sin(s.a);ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}resize();draw();addEventListener("resize",resize);
function petals(){const box=document.querySelector(".petals");for(let i=0;i<18;i++){let p=document.createElement("i");p.className="petal";p.style.left=Math.random()*100+"%";p.style.animationDuration=(7+Math.random()*8)+"s";p.style.animationDelay=Math.random()*8+"s";box.appendChild(p)}}petals();
document.getElementById("wishBtn").onclick=()=>{document.querySelector(".cake").classList.add("blown");document.getElementById("wishText").textContent="Wish made. ✨ May every beautiful thing you wish for find its way to you.";confetti()};
function confetti(){for(let i=0;i<90;i++){let e=document.createElement("i");e.className="conf";e.style.setProperty("--x",(Math.random()*600-300)+"px");e.style.setProperty("--y",(Math.random()*-500+100)+"px");e.style.background=["#f2dce5","#e9b7c7","#d4c2ef","#f6d99c"][i%4];e.style.transform=`rotate(${Math.random()*180}deg)`;document.getElementById("confetti").appendChild(e);setTimeout(()=>e.remove(),1900)}}
document.getElementById("secretBtn").onclick=()=>{document.getElementById("secretMessage").classList.add("show");document.getElementById("lock").textContent="🔓";document.getElementById("secretBtn").textContent="Message unlocked ♥"};
const music=document.getElementById("music"),musicBtn=document.getElementById("musicBtn");musicBtn.onclick=()=>{if(music.paused){music.play().catch(()=>{});musicBtn.textContent="Ⅱ Pause music"}else{music.pause();musicBtn.textContent="♪ Play a little music"}};
